### ISSUE TITLE
Display a loading gif when image and sound is bufferring

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku-desktop#6]

**Comment by PezCoder** [comment]
I just tried this, loved the desktop app..
I would like to work on this.

**Comment by PezCoder** [comment]
Need to clarify few things before starting:
1. **Look of loading:** What kind of loading animation are you expecting, do you have something in mind ? or I can try to build some CSS based loading to match your current UI & we can see from there
2. **Behaviour of loading:** 
1. Show the loading when image/sound is loading
2. The loader should replace play/pause button (this is how youtube does it)

**Comment by anshumanv** [comment]
Hey, @PezCoder! welcome onboard 😄 
I'm glad you liked the app.
As for the animation, I have no such preferences. You can approach it the way it looks good to you.
Also, Behavior of loading is exactly how you stated it.

**Comment by PezCoder** [comment]
@anshumanv I've done the loader based on just the music, There could be times when music is loaded & since the image is heavy it might not load.
Show both loader & play buttons might confuse the user.
Also I think the major functionality is the audio in the website & that's what the loader should be for hence I kept it just for the audio.
